### PR TITLE
feat: use cainome abigen

### PR DESCRIPTION
**Pull request by glihm**
This PR aims at refactoring the contract interaction using `abigen!` macro from `cainome`.

Currently in draft, @neotheprogramist which versions of starknet and rpc version do you use to install the `devnet`?

The test using it is failing with this error:
```
---- tests::webauthn_signer_test::test_verify_webauthn_signer stdout ----
called `Result::unwrap()` on an `Err` value: Provider(Other(JsonRpcError(JsonRpcError { code: -32602, message: "invalid type: string \"pending\", expected a sequence", data: None })))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I've run this:
```
STARKNET_VERSION=0.12.2 RPC_SPEC_VERSION=0.5.1 cargo install --git https://github.com/0xSpaceShard/starknet-devnet-rs.git --locked
```
I want to be sure I'm not breaking anything in this test as it's one of the most important actually.

### CODE REVIEW

**Comment by glihm** [comment]
@neotheprogramist ah.. I think it's due to the bump of `starknet-rs` to `0.8.0`. Will investigate.

**Comment by neotheprogramist** [comment]
@glihm 
We had problems since yesterday with starknet-devnet-rs.
We will try to use docker and that might help, will let you know.

**Comment by glihm** [comment]
@neotheprogramist I've switched to Katana on this PR, and the test passes fine.
Would appreciate the review and let me know if you prefer to merge yours first, I'll rebase then. :+1:

**Review by ThePinion — APPROVED** [review]
Everything seems fine to me :)). There were some problems in the previous version of katana, but it seems that they were fixed with the recent update.

**Review by matzayonc — APPROVED** [review]

**Pull request merged**
